package com.wael.janlandonlam;

import android.app.*;import android.os.*;import android.view.*;import android.graphics.*;import android.content.*;import java.util.*;

public class MainActivity extends Activity{
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);setContentView(new Game(this));}
}

class Game extends View{
 Paint p=new Paint(1); Random r=new Random(1234); ArrayList<Gate> gates=new ArrayList<>();
 int screen=0,level=1,page=0,score=0,best=0,unlocked=1; float y,scroll; boolean press=false,dead=false,won=false;
 Game(Context c){super(c);p.setTypeface(Typeface.create("sans",Typeface.BOLD));setBackgroundColor(Color.BLACK);}
 void startLevel(int l){level=Math.max(1,Math.min(100,l));score=0;scroll=0;dead=false;won=false;y=getHeight()>0?getHeight()/2f:700;gates.clear();float spacing=360f-Math.min(100,level)*0.9f;float center=getHeight()>0?getHeight()/2f:700;for(int i=0;i<28;i++){center+=((i%5)-2)*18;gates.add(new Gate(720+i*spacing,center));}screen=1;invalidate();}
 @Override protected void onDraw(Canvas c){super.onDraw(c);int w=getWidth(),h=getHeight();c.drawColor(Color.rgb(5,8,20));drawGrid(c,w,h);if(screen==0){drawMenu(c,w,h);return;}drawGame(c,w,h);invalidate();}
 void drawGrid(Canvas c,int w,int h){p.setStrokeWidth(2);p.setColor(Color.rgb(17,32,58));for(int x=0;x<w;x+=72)c.drawLine(x,0,x,h,p);for(int yy=0;yy<h;yy+=72)c.drawLine(0,yy,w,yy,p);}
 void drawMenu(Canvas c,int w,int h){p.setTextAlign(Paint.Align.CENTER);p.setColor(Color.WHITE);p.setTextSize(48);c.drawText("JANA1234",w/2,100,p);p.setTextSize(30);p.setColor(Color.CYAN);c.drawText("Levels Waves",w/2,140,p);p.setTextSize(22);p.setColor(Color.LTGRAY);c.drawText("100 LEVELS",w/2,185,p);int first=page*10+1;for(int i=0;i<10;i++){int n=first+i;float cy=250+i*92;if(n>100)break;p.setColor(n<=unlocked?0xFF10CFE8:0xFF26354C);c.drawRoundRect(w*.18f,cy-33,w*.82f,cy+33,22,22,p);p.setColor(Color.WHITE);p.setTextSize(24);c.drawText("LEVEL "+n,w/2,cy+8,p);}p.setTextSize(20);p.setColor(Color.LTGRAY);c.drawText("<  PAGE "+(page+1)+" / 10  >",w/2,h-55,p);}
 void drawGame(Canvas c,int w,int h){float speed=5.4f+Math.min(4.2f,(level-1)*0.035f);float wave=5.8f+Math.min(2.8f,(level-1)*0.022f);float corridor=Math.max(240f,520f-(level-1)*2.3f);float spacing=360f-Math.min(100,level)*0.9f;float finish=6800f+level*22f;
  if(!dead&&!won){y+=press?-wave:wave;scroll+=speed;score=(int)(100f*scroll/finish);if(y<34||y>h-34)dead=true;if(scroll>=finish){won=true;score=100;unlocked=Math.max(unlocked,Math.min(100,level+1));}}
  for(Gate g:gates){float x=g.x-scroll;if(x<-120){g.x+=gates.size()*spacing;float amp=Math.min(h*.22f,120+level*1.4f);g.cy=h/2f+(float)Math.sin((g.x/spacing)*0.85f+level*.3f)*amp;}x=g.x-scroll;if(x>-120&&x<w+120){float top=g.cy-corridor/2,bottom=g.cy+corridor/2;p.setColor(0xFFFF2A93);c.drawRect(x-29,0,x+29,top,p);p.setColor(0xFF00D8FF);c.drawRect(x-29,bottom,x+29,h,p);drawSpikes(c,x,top,bottom);if(Math.abs(x-w*.25f)<40&&(y<top+20||y>bottom-20))dead=true;}}
  drawHero3D(c,w*.25f,y,press);p.setTextAlign(Paint.Align.CENTER);p.setColor(Color.WHITE);p.setTextSize(27);c.drawText("JANA1234 Levels Waves",w/2,48,p);p.setTextSize(21);c.drawText("LEVEL "+level+"   •   "+Math.max(0,Math.min(100,score))+"%",w/2,80,p);
  if(dead||won){p.setColor(0xD8080B18);c.drawRoundRect(35,h/2-180,w-35,h/2+180,30,30,p);p.setColor(Color.WHITE);p.setTextSize(46);c.drawText(won?"LEVEL COMPLETE!":"CRASH!",w/2,h/2-78,p);p.setTextSize(24);c.drawText(won?"Tap for next level":"Tap to retry",w/2,h/2-15,p);p.setColor(Color.CYAN);c.drawText("Top-left = levels",w/2,h/2+70,p);}else{p.setTextSize(18);p.setColor(Color.LTGRAY);c.drawText("HOLD = UP   •   RELEASE = DOWN",w/2,h-28,p);} }
 void drawSpikes(Canvas c,float x,float top,float bottom){p.setColor(Color.WHITE);for(int k=0;k<3;k++){float sx=x-27+k*22;Path a=new Path();a.moveTo(sx,top);a.lineTo(sx+10,top+17);a.lineTo(sx+20,top);a.close();c.drawPath(a,p);Path b=new Path();b.moveTo(sx,bottom);b.lineTo(sx+10,bottom-17);b.lineTo(sx+20,bottom);b.close();c.drawPath(b,p);}}
 void drawHero3D(Canvas c,float x,float yy,boolean up){float tilt=up?-4:4;p.setColor(0xFF006C8C);Path shadow=new Path();shadow.moveTo(x-30,yy+tilt);shadow.lineTo(x+18,yy-24+tilt);shadow.lineTo(x+18,yy-10+tilt);shadow.lineTo(x+34,yy+tilt);shadow.lineTo(x+18,yy+10+tilt);shadow.lineTo(x+18,yy+24+tilt);shadow.close();c.drawPath(shadow,p);p.setColor(0xFF22E9FF);Path face=new Path();face.moveTo(x-34,yy-4+tilt);face.lineTo(x+18,yy-30+tilt);face.lineTo(x+18,yy-12+tilt);face.lineTo(x+37,yy-4+tilt);face.lineTo(x+18,yy+5+tilt);face.lineTo(x+18,yy+22+tilt);face.close();c.drawPath(face,p);p.setColor(0xFF9AFAFF);Path hi=new Path();hi.moveTo(x-34,yy-4+tilt);hi.lineTo(x+18,yy-30+tilt);hi.lineTo(x+18,yy-12+tilt);hi.lineTo(x-2,yy-3+tilt);hi.close();c.drawPath(hi,p);}
 @Override public boolean onTouchEvent(MotionEvent e){float x=e.getX(),yy=e.getY();if(e.getAction()==MotionEvent.ACTION_DOWN){if(screen==0){if(yy>getHeight()-100){if(x<getWidth()/2f)page=Math.max(0,page-1);else page=Math.min(9,page+1);invalidate();return true;}int first=page*10+1;for(int i=0;i<10;i++){float cy=250+i*92;if(yy>cy-42&&yy<cy+42){int n=first+i;if(n<=unlocked&&n<=100)startLevel(n);return true;}}return true;}if(dead||won){if(x<getWidth()*.28f&&yy<getHeight()*.25f){screen=0;page=(level-1)/10;invalidate();return true;}if(won&&level<100)startLevel(level+1);else startLevel(level);return true;}press=true;}else if(e.getAction()==MotionEvent.ACTION_UP||e.getAction()==MotionEvent.ACTION_CANCEL)press=false;return true;}
 static class Gate{float x,cy;Gate(float x,float cy){this.x=x;this.cy=cy;}}
}
